geography_df <- data.frame(
  row_number = 1:17,
  geographic_level = c(
    "National",
    "Regional",
    "Local authority",
    "Local authority district",
    "RSC region",
    "Parliamentary constituency",
    "Local skills improvement plan area",
    "Local enterprise partnership",
    "English devolved area",
    "Opportunity area",
    "Ward",
    "MAT",
    "Sponsor",
    "School",
    "Provider",
    "Institution",
    "Planning area"
  ),
  code_field = c(
    "country_code",
    "region_code",
    "new_la_code",
    "lad_code",
    NA,
    "pcon_code",
    "lsip_code",
    "local_enterprise_partnership_code",
    "english_devolved_area_code",
    "opportunity_area_code",
    "ward_code",
    "trust_id",
    "sponsor_id",
    "school_urn",
    "provider_ukprn",
    "institution_id",
    "planning_area_code"
  ),
  name_field = c(
    "country_name",
    "region_name",
    "la_name",
    "lad_name",
    "rsc_region_lead_name",
    "pcon_name",
    "lsip_name",
    "local_enterprise_partnership_name",
    "english_devolved_area_name",
    "opportunity_area_name",
    "ward_name",
    "trust_name",
    "sponsor_name",
    "school_name",
    "provider_name",
    "institution_name",
    "planning_area_name"
  ),
  code_field_secondary = c(
    NA,
    NA,
    "old_la_code",
    NA,
    NA,
    NA,
    NA,
    NA,
    NA,
    NA,
    NA,
    NA,
    NA,
    "school_laestab",
    NA,
    NA,
    NA
  )
)

usethis::use_data(geography_df, overwrite = TRUE)
