---
title: "check_assumptions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{check_assumptions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette is mostly aimed at package developers, though will be useful for anyone who wants to use any of the individaul `precheck_*()` or `check_*()` functions in isolation. 

If you are the latter, using any checks individually outside of a `screen_*()` wrapper function, proceed with caution and read this article first.

## What assumptions?

1. Only the `screen_*()` functions have argument validation

At the time the package was first developed there were already 90+ checks in the screener. It would be inefficient to revalidate the arguments in every check, for example checking that the datafile is a data.frame 90+ times.

Therefore we only provide argument validation for the top level `screen_*()` functions.

2. Within all of the the `screen_*()` functions, individual checks are placed in a specific order, and broken up by stages. 

This means the tests can fail early, giving quicker feedback if there's fundamental issues, and also means the later checks can be more lightweight and 'assume' certain things about the data.frame that is being tested.

For example, `precheck_meta_col_type()` requires the `col_type` column to be present, though as this is already checked for in `...` we minimise duplicating that check by not rechecking that column is present.

## Starting assumptions

Filename checks can be carried out in isolation from other checks. The `screen_filenames()` function can be ran in a single line on two simple strings where needed.

Metadata files are checked first, as they are fast and can give immediate feedback, though they are also crucial for understanding and checking the data file, so we need to have a passing metadata file before we can test the data file.

## Precheck versus check

Most groups have a `precheck_*()` grouping, e.g. `precheck_time_*()` and `check_time_*()`. If the `precheck_*()` functions are not ran first, there is every chance that you could get unexpected errors in the `check_*()` functions.

For example

...
