---
title: "common_issues"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{common_issues}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

A guide to common issues with files and code to support debugging the problems within the file.

## Duplicate rows

The accuracy of this check has been questioned by many, many analysts over the years. Without fail, it has prevailed, exposing case after case of duplication. So, leave your indignation at the door, and follow this guide to find your duplicate rows.

The `check_data_duplicate_rows()` function checks for duplicate rows across the time, geography and filter columns. This is to make sure that there is only one possible value for any combination of categories per indicator.

An example table that does not have duplicate rows overall, but fails the `check_data_duplicate_rows()` function:
``` r
data.frame(
  time_period = c(2020, 2020),
  time_identifier = c("Calendar year", "Calendar year"),
  geographic_level = c("National", "National"),
  country_code = c("E92000001", "E92000001"),
  country_name = c("England", "England"),
  school_count = c(10, 20)
)
```

This kind of file causes a big issue for users, as they don't know which value is the real value, leading to confusion and risk of misrepresentation.

To find the duplicates in your file, use the ... argument in the ... function, like below.

``` r

```

## Pound symbols

...
