FROM r-base:latest

RUN \
  apt update && \
  \
  apt install -y \
    libssl-dev \
    libcurl4-openssl-dev \
    libxml2-dev \
    libfreetype6-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libpng-dev \
    libcairo2-dev \
    pkg-config \
    libtiff5-dev \
    libjpeg-dev \
    libwebp-dev \
    build-essential && \
  \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY DESCRIPTION /tmp/DESCRIPTION

RUN Rscript -e "install.packages(c('devtools', 'desc', 'pak')); desc::desc_get_deps(file = '/tmp/DESCRIPTION')[['package']] |> setdiff(c('R', 'base')) |> pak::pak()"
