#' EES-ily generate some beefy test files
#'
#' Mostly for ease of performance benchmarking. A bit crude, only does
#' PCons for simplicity so far.
#'
#' @param years A vector of 4 digit years
#' @param pcon_names A vector of PCon names
#' @param pcon_codes A vector of PCon codes
#' @param num_filters The number of filters to generate, currently
#' will give each filter 8 items
#' @param num_indicators The number of indicators to generate, currently
#' generates random numbers between 100 and 1000
#'
#' @export
#' @return A list containing two data frames, one data and associated meta
#'
#' @examples
#' generate_test_dfs(2010:2015, "Sheffield Central", "E14000919", 2, 3)
generate_test_dfs <- function(
    years = 3000,
    pcon_names = "Sheffield Central",
    pcon_codes = "E14000919",
    num_filters = 1,
    num_indicators = 1) {
  file_pair <- list(
    data = generate_data_file(
      years, pcon_names, pcon_codes, num_filters, num_indicators
    ),
    meta = generate_meta_file(num_filters, num_indicators)
  )

  return(file_pair)
}

#' Generate a data file for testing
#'
#' This function is designed to be used within `generate_test_dfs` to
#' complement the meta file generated by `generate_meta_file`.
#'
#' Use the parameters to quickly create beefy files!
#'
#' @keywords internal
#'
#' @inheritParams generate_test_dfs
#'
#' @returns A data frame following the EES data standards
generate_data_file <- function(
    years,
    pcon_names,
    pcon_codes,
    num_filters,
    num_indicators) {
  test_data <- data.frame(
    time_period = rep(years, each = length(pcon_codes) * (num_filters * 8)),
    time_identifier = "Calendar year",
    geographic_level = "Parliamentary constituency",
    country_name = "England",
    country_code = "E92000001",
    pcon_name = rep(pcon_names, times = length(years * (num_filters * 8))),
    pcon_code = rep(pcon_codes, times = length(years * (num_filters * 8)))
  )

  filter_multiplier <- ifelse(num_filters == 1, 1, (num_filters - 1) * 8)

  for (i in 1:num_filters) {
    test_data[[paste0("filter", i)]] <- sample(
      rep(
        c(
          "Alpha", "Bravo", "Charlie", "Delta",
          "Echo", "Foxtrot", "Golf", "Hotel"
        ),
        times = length(years) * length(pcon_codes) * filter_multiplier
      ),
      nrow(test_data),
      replace = TRUE
    )
  }

  for (i in 1:num_indicators) {
    test_data[[paste0("indicator", i)]] <- sample(
      100:1000,
      nrow(test_data),
      replace = TRUE
    )
  }

  return(test_data)
}

#' Generate a meta file for testing
#'
#' This function is designed to be used within `generate_test_dfs` to
#' complement the data file generated by `generate_data_file`.
#'
#' @param num_filters The number of filters to generate
#' @param num_indicators The number of indicators to generate
#'
#' @keywords internal
#' @returns A data frame following the EES metadata standards
generate_meta_file <- function(
    num_filters,
    num_indicators) {
  cols <- c(
    paste0("filter", 1:num_filters),
    paste0("indicator", 1:num_indicators)
  )

  meta <- data.frame(
    col_name = cols,
    col_type = ifelse(grepl("^filter", cols), "Filter", "Indicator"),
    label = toupper(cols),
    indicator_grouping = NA,
    indicator_unit = NA,
    indicator_dp = NA,
    filter_hint = NA,
    filter_grouping_column = NA
  )

  return(meta)
}
